### PR TITLE
adding affinity for CI

### PR DESCRIPTION
**Pull request by denisok**
Adding affinity for CI system.

### CODE REVIEW

**Review by jan--f — COMMENTED** [review]
Looks reasonable to me. I assume `suse-master` is going to be our CI branch? Otherwise a more extensive commit message might make sense.

**Comment by denisok** [comment]
@jan--f good question. As our CI would have "branch" parameter - we could now do testing of PRs. Not automatic so far - but I don't see many of them so far, and as all work is done upstream - don't know if we would have any.

We need to find out what would be our release procedure starting from the source code.

**Comment by BlaineEXE** [comment]
I've been instructing other teams in suse to use this `suse-master` branch to run upstream rook on CaaSP, so definitely don't merge CI changes that might break things for others here.

I would suggest that the best alternate approach would be to have a separate CI branch that you can feel free to merge into it as much as you like. Starting the CI branch as a fork of suse-master would be a good starting point, imo.

As a thought for the future, when we start dealing with running CI against different branches, we may need to change the specs to replace the `image` fields with placeholder values that are replaced with `sed` in part of the CI setup.

**Comment by kshtsk** [comment]
> I've been instructing other teams in suse to use this `suse-master` branch to run upstream rook on CaaSP, so definitely don't merge CI changes that might break things for others here.
> 
This is non-sense, because CI's purpose is to validate the product is working it should not have anything that breaks something to others. If it has, then the design of the code is wrong.

> I would suggest that the best alternate approach would be to have a separate CI branch that you can feel free to merge into it as much as you like. Starting the CI branch as a fork of suse-master would be a good starting point, imo.
> 
Having a separate CI branch with "CI specific changes" is the worst thing you can do.
CI is actually not just a job in some CI systems, it approach of testing and merging of code to working/production system as fast as possible.
 
> As a thought for the future, when we start dealing with running CI against different branches, we may need to change the specs to replace the `image` fields with placeholder values that are replaced with `sed` in part of the CI setup.

**Pull request closed without merging**
